# Generated by Django 6.1.1 on 2026-09-19 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_show', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'fund_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('horizon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_show', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='mutual_fund.fundcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'fund_subcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundAMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bse_amc_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='amc_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'mutual_fund_amc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=255)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('nfo_dates', models.DateField(blank=True, null=True)),
                ('nfo_end_date', models.DateField(blank=True, null=True)),
                ('redemption_date', models.DateField(blank=True, null=True)),
                ('stated_benchmark', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_objective', models.TextField(blank=True, null=True)),
                ('fund_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('managed_from', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('show_on_site', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_masters', to='mutual_fund.fundsubcategory')),
                ('fund_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_masters', to='mutual_fund.mutualfundamc')),
            ],
            options={
                'db_table': 'mutual_fund_master',
            },
        ),
        migrations.CreateModel(
            name='MutualFundsScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('fund_type', models.CharField(choices=[('OPEN_ENDED', 'Open Ended Scheme'), ('CLOSE_ENDED', 'Close Ended Scheme'), ('INTERVAL', 'Interval')], default='', max_length=30, verbose_name='Fund Type')),
                ('option', models.CharField(blank=True, choices=[('GROWTH', 'Growth'), ('IDCW', 'IDCW'), ('IDCW_PAYOUT', 'IDCW Payout'), ('IDCW_REINVESTMENT', 'IDCW Reinvestment')], max_length=30, null=True, verbose_name='Option')),
                ('plans', models.CharField(blank=True, choices=[('DIRECT', 'Direct'), ('REGULAR', 'Regular')], max_length=30, null=True)),
                ('amfi_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bse_unique_no', models.IntegerField(db_index=True, unique=True)),
                ('scheme_code', models.CharField(db_index=True, max_length=100)),
                ('amc_scheme_code', models.CharField(blank=True, max_length=100, null=True)),
                ('isin_code', models.CharField(db_index=True, max_length=12)),
                ('rta_code', models.CharField(blank=True, max_length=100, null=True)),
                ('rta_scheme_code', models.CharField(blank=True, max_length=100, null=True)),
                ('register_agent', models.CharField(blank=True, choices=[('CAMS', 'CAMS'), ('KARVY', 'Karvy')], max_length=30, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('LOW_TO_MODERATE', 'Low to Moderate'), ('MODERATE', 'Moderate'), ('MODERATELY_HIGH', 'Moderately High'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('purchase_allowed', models.BooleanField(default=True)),
                ('purchase_transaction_mode', models.CharField(help_text='DP (Demat & Physical) / D (Demat) / P (Physical)', max_length=10)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('additional_investment', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('max_purchase_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('purchase_amount_multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('purchase_cutoff_time', models.TimeField(blank=True, null=True)),
                ('redemption_allowed', models.BooleanField(default=True)),
                ('redemption_transaction_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('min_redemption_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('redemption_qty_multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('max_redemption_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('min_redemption_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('max_redemption_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('redemption_amount_multiple', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('redemption_cutoff_time', models.TimeField(blank=True, null=True)),
                ('settlement_type', models.CharField(help_text='T1, T2, L1 etc.', max_length=10)),
                ('is_amc_active', models.BooleanField(default=True)),
                ('is_dividend_reinvestment', models.BooleanField(default=False)),
                ('is_sip_allowed', models.BooleanField(default=False)),
                ('is_stp_allowed', models.BooleanField(default=False)),
                ('is_swp_allowed', models.BooleanField(default=False)),
                ('is_switch_allowed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reopening_date', models.DateField(blank=True, null=True)),
                ('has_exit_load', models.BooleanField(default=False)),
                ('exit_load_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_lock_in', models.BooleanField(default=False)),
                ('lock_in_period_days', models.IntegerField(default=0)),
                ('channel_partner_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='mutual_fund.mutualfundmaster')),
            ],
            options={
                'db_table': 'mutual_fund_scheme',
                'ordering': ['scheme_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='fundsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_per_category'),
        ),
        migrations.AddIndex(
            model_name='mutualfundsscheme',
            index=models.Index(fields=['scheme_name'], name='mutual_fund_scheme__d55225_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundsscheme',
            index=models.Index(fields=['bse_unique_no'], name='mutual_fund_bse_uni_385299_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundsscheme',
            index=models.Index(fields=['scheme_code'], name='mutual_fund_scheme__f92e98_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundsscheme',
            index=models.Index(fields=['isin_code'], name='mutual_fund_isin_co_cc2ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundsscheme',
            index=models.Index(fields=['purchase_allowed'], name='mutual_fund_purchas_af2dbb_idx'),
        ),
    ]
