# Generated by Django 6.1.1 on 2026-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundsscheme',
            name='isin_payout',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundsscheme',
            name='isin_reinvest',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundsscheme',
            name='isin_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
