# Generated by Django 6.1.1 on 2026-09-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundportfolioStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarage_maturity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modified_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_to_maturity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('portfolio_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_bookval', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset_allocation', models.JSONField(blank=True, null=True)),
                ('market_cap_weightage', models.JSONField(blank=True, null=True)),
                ('holdings', models.JSONField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('scheme_category', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_categorylabel', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_risk', models.CharField(blank=True, max_length=255, null=True)),
                ('benchmark_index', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_load_msg', models.TextField(blank=True, null=True)),
                ('fund_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('_52_week_low_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('_52_week_low_nav_date', models.DateField(blank=True, null=True)),
                ('_52_week_high_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('_52_week_high_nav_date', models.DateField(blank=True, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('nav_closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='mutual_fund.mutualfundmaster')),
            ],
            options={
                'db_table': 'mutual_fund_portfolio_stat',
                'ordering': ['-updated'],
                'indexes': [models.Index(fields=['fund'], name='mutual_fund_fund_id_8a3ce3_idx'), models.Index(fields=['nav_closed'], name='mutual_fund_nav_clo_00605f_idx')],
                'constraints': [models.UniqueConstraint(fields=('fund',), name='unique_stat_per_fund')],
            },
        ),
    ]
