# Generated by Django 6.1.1 on 2026-09-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund', '0002_mutualfundsscheme_isin_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundNavSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('no_data', 'No real NAV for date (holiday / weekend / not yet published) - carried forward'), ('failed', 'Failed')], default='running', max_length=10)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('active_schemes', models.PositiveIntegerField(default=0)),
                ('rows_in_feed', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('carried_forward_count', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('unmapped_count', models.PositiveIntegerField(default=0)),
                ('skipped_closed_count', models.PositiveIntegerField(default=0)),
                ('parse_error_count', models.PositiveIntegerField(default=0)),
                ('newly_closed_count', models.PositiveIntegerField(default=0)),
                ('total_closed', models.PositiveIntegerField(default=0)),
                ('closed_but_reporting', models.PositiveIntegerField(default=0)),
                ('stats_computed', models.PositiveIntegerField(default=0)),
                ('stats_failed', models.PositiveIntegerField(default=0)),
                ('stats_skipped_closed', models.PositiveIntegerField(default=0)),
                ('missing_amfi_codes', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'mutual_fund_nav_sync_log',
                'ordering': ['-nav_date'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='mutual_fund.mutualfundsscheme')),
            ],
            options={
                'db_table': 'mutual_fund_nav',
                'indexes': [models.Index(fields=['nav_date'], name='ix_mf_nav_date')],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'nav_date'), name='uq_mf_nav_scheme_date')],
            },
        ),
        migrations.CreateModel(
            name='MutualFundReturnStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('latest_nav', models.DecimalField(decimal_places=4, max_digits=15)),
                ('first_nav_date', models.DateField(blank=True, null=True)),
                ('ret_1w', models.FloatField(blank=True, null=True)),
                ('ret_1m', models.FloatField(blank=True, null=True)),
                ('ret_3m', models.FloatField(blank=True, null=True)),
                ('ret_6m', models.FloatField(blank=True, null=True)),
                ('ret_ytd', models.FloatField(blank=True, null=True)),
                ('ret_1y', models.FloatField(blank=True, null=True)),
                ('ret_3y', models.FloatField(blank=True, null=True)),
                ('ret_5y', models.FloatField(blank=True, null=True)),
                ('cagr_3y', models.FloatField(blank=True, null=True)),
                ('cagr_5y', models.FloatField(blank=True, null=True)),
                ('cagr_10y', models.FloatField(blank=True, null=True)),
                ('cagr_since_inception', models.FloatField(blank=True, null=True)),
                ('volatility_1y', models.FloatField(blank=True, null=True)),
                ('volatility_3y', models.FloatField(blank=True, null=True)),
                ('max_drawdown_1y', models.FloatField(blank=True, null=True)),
                ('max_drawdown_3y', models.FloatField(blank=True, null=True)),
                ('sharpe_3y', models.FloatField(blank=True, null=True)),
                ('sortino_3y', models.FloatField(blank=True, null=True)),
                ('high_52w', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('high_52w_date', models.DateField(blank=True, null=True)),
                ('low_52w', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('low_52w_date', models.DateField(blank=True, null=True)),
                ('calendar_returns', models.JSONField(blank=True, null=True)),
                ('pct_1y', models.FloatField(blank=True, null=True)),
                ('pct_3y', models.FloatField(blank=True, null=True)),
                ('pct_5y', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_stat', to='mutual_fund.mutualfundsscheme')),
            ],
            options={
                'db_table': 'mutual_fund_return_stat',
                'indexes': [models.Index(fields=['-ret_1y'], name='mutual_fund_ret_1y_0b0c1f_idx'), models.Index(fields=['-cagr_3y'], name='mutual_fund_cagr_3y_d2b909_idx'), models.Index(fields=['-cagr_5y'], name='mutual_fund_cagr_5y_674207_idx'), models.Index(fields=['volatility_3y'], name='mutual_fund_volatil_3c43b6_idx')],
            },
        ),
    ]
