# Generated by Django 6.1.1 on 2026-10-06 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutual_fund', '0003_mutualfundnavsynclog_mutualfundnav_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CASFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('folio_number', models.CharField(db_index=True, max_length=100)),
                ('amc_name', models.CharField(blank=True, max_length=255)),
                ('investor_name', models.CharField(blank=True, max_length=255)),
                ('investor_pan', models.CharField(blank=True, db_index=True, max_length=10)),
                ('kyc_status', models.CharField(blank=True, max_length=50)),
                ('pan_kyc_status', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cas_folio',
                'ordering': ['amc_name', 'folio_number'],
            },
        ),
        migrations.CreateModel(
            name='CASSchemeHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('scheme_name', models.CharField(max_length=500)),
                ('advisor', models.CharField(blank=True, max_length=100)),
                ('rta_code', models.CharField(blank=True, max_length=100)),
                ('rta_name', models.CharField(blank=True, max_length=100)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=20)),
                ('amfi_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('opening_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('closing_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('calculated_closing_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('nominees', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_scheme_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_holdings', to='cas_parser.casfolio')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cas_holdings', to='mutual_fund.mutualfundsscheme')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cas_scheme_holding',
                'ordering': ['scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='CASStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('statement_type', models.CharField(choices=[('CAS', 'CAS'), ('CDSL', 'CDSL'), ('NSDL', 'NSDL'), ('UNKNOWN', 'Unknown')], default='CAS', max_length=20)),
                ('statement_from', models.DateField(blank=True, null=True)),
                ('statement_to', models.DateField(blank=True, null=True)),
                ('investor_name', models.CharField(blank=True, max_length=255)),
                ('investor_pan', models.CharField(blank=True, db_index=True, max_length=10)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='cas_statements/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('parser_version', models.CharField(blank=True, max_length=100)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('processing_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cas_statement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='casfolio',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='cas_parser.casstatement'),
        ),
        migrations.CreateModel(
            name='CASTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('transaction_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dividend_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('gift_folio', models.CharField(blank=True, max_length=100)),
                ('transaction_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cas_parser.casschemeholding')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cas_transaction',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CASValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', verbose_name='Updated At')),
                ('valuation_date', models.DateField()),
                ('nav', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='cas_parser.casschemeholding')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cas_valuation',
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='casschemeholding',
            index=models.Index(fields=['folio', 'scheme_name'], name='cas_scheme__folio_i_971670_idx'),
        ),
        migrations.AddIndex(
            model_name='casschemeholding',
            index=models.Index(fields=['isin', 'amfi_code'], name='cas_scheme__isin_31fc54_idx'),
        ),
        migrations.AddConstraint(
            model_name='casschemeholding',
            constraint=models.UniqueConstraint(fields=('folio', 'isin', 'scheme_name'), name='unique_folio_scheme_isin'),
        ),
        migrations.AddConstraint(
            model_name='casstatement',
            constraint=models.UniqueConstraint(fields=('user', 'file_hash'), name='unique_user_cas_file_hash'),
        ),
        migrations.AddConstraint(
            model_name='casfolio',
            constraint=models.UniqueConstraint(fields=('statement', 'folio_number', 'amc_name'), name='unique_statement_folio_amc'),
        ),
        migrations.AddIndex(
            model_name='castransaction',
            index=models.Index(fields=['holding', 'transaction_date'], name='cas_transac_holding_ac2671_idx'),
        ),
        migrations.AddIndex(
            model_name='castransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='cas_transac_transac_d52f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='castransaction',
            constraint=models.UniqueConstraint(fields=('holding', 'transaction_hash'), name='unique_holding_transaction_hash'),
        ),
        migrations.AddConstraint(
            model_name='casvaluation',
            constraint=models.UniqueConstraint(fields=('holding', 'valuation_date'), name='unique_holding_valuation_date'),
        ),
    ]
